# Fork of https://github.com/le4ker/personal-jekyll-theme/network/members

# Site settings

# NB! Set your site's url, otherwise stuff will break :)

# url: "https://koenbal.github.io"  # when using github pages without a custom domain
url: "https://koenbal.com"          # when using github pages with a custom domain

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl:personal_website  # when using github pages without a custom domain
baseurl:                    # when using github pages with a custom domain
  
# Google tracking id

google-tracking-id: "UA-154989443-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Koen Bal"
title: "Koen Bal"
description: "Website of Koen Bal. Opinions expressed are mine."
keywords: "bal, Koen, personal, website"
favicon: "/img/favicon.ico"

################
# Header layout #
################

black-favicon: ""
# "/img/black-lab-glass.ico"

background-img: "../img/cubes-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
delete-speed: -30
start-delay: 500
delete-delay: 2500
lines: # You can add HTML Tags in the Text
# Me
  - text: "Welcome to the best Koen Bal site on the internet.^500<br/> Feel free to have a look around."
# Quotes
  - text: "Everybody is a genius.^500<br/> But if you judge a fish by its ability to climb a tree,^500<br/> it will live its whole life believing that it is stupid.^500<br/> — Albert Einstein"
  - text: "Live for what’s worth dying for,^500<br/> and leverage technology to create the world you wish to see.^500<br/> — Gandhi modernized"
  - text: "A life spent making mistakes is not only more honorable,^500<br/> but more useful than a life spent doing nothing.^500<br/> — George Bernhard Shaw"
  - text: "He who fears he will suffer,^500<br/> already suffers because he fears.^500<br/> — Michel De Montaigne"
  - text: "In seeking happiness for others,^500<br/> you will find it in yourself.^500<br/> — Unknown"
  - text: "If you don’t like something, change it.^500<br/> If you can’t change it, change the way you think about it.^500<br/> — Mary Engelbreit"
  - text: "Life is never made unbearable by circumstances,^500<br/> but only by lack of meaning and purpose.^500<br/> — Viktor Frankl"
  - text: "If you want happiness for an hour — take a nap.^500<br/> If you want happiness for a day — go fishing.^500<br/> If you want happiness for a year — inherit a fortune.^500<br/> If you want happiness for a life time — help someone else.^500<br/> — Chinese proverb"
  - text: "My wealth is not measured in how much time I have to do what I want,^500<br/> rather, how much meaning I’m able to derive from the time I have.^500<br/> — Henry van Dyke modernized"
  - text: "When one door of happiness closes, another opens,^500<br/> but often we look so long at the closed door that we do not see the one that has been opened for us.^500<br/> — Helen Keller"
  - text: "Most people do not listen with the intent to understand;^500<br/> they listen with the intent to reply.^500<br/> — Stephen Covey"
  - text: "Challenges are what make life interesting^500<br/> and overcoming them is what makes life meaningful.^500<br/> — Joshua J. Marine"
  - text: "A mind that is stretched by a new experience can never go back to its old dimensions.^500<br/> — Oliver Wendell Holmes"
  - text: "The only way that we can live is if we grow.^500<br/> The only way we can grow is if we change.^500<br/> The only way we can change is if we learn.^500<br/> The only way we can learn is if we are exposed.^500<br/> And the only way that we are exposed is if we throw ourselves into the open.^500<br/> — C. Joybell"
  - text: "I would rather die a meaningful death than to live a meaningless life.^500<br/> — Corazon Aquino"  
  - text: "Happiness isn’t something that’s achieved,^500<br/> it’s a skill that’s cultivated and practiced daily.^500<br/> It’s mastery comes from serving others.^500<br/> — Chinese proverb modernized"

  # more: https://medium.com/swlh/21-of-the-worlds-most-powerful-quotes-updated-for-today-and-tomorrow-6b7634358c2
  
# Protips
  # - text: "Protip:^500 Never... ^500<br />Ever... ^500<br /> take protips from a guy on the internet."

# Hope
  # - text: "I would like to live forever,^500,<br />or at least as long as possible."

# Bad Jokes
  - text: "Buckle up, bad jokes coming..."
  - text: "Keep staring at the screen.^500<br />These are funny.^500<br />At least my gf told me they were."
  - text: "I wrote a Haiku.^500<br />Okay, maybe I did^500n't.^500<br /> Wait,^1000 I think I did."
  - text: "Okay,^500 last one.^500<br />Promise."
  - text: "These things load in a random order.^500<br />But once you see the same one twice it means they're repeating.^500<br />You can stop after that."

# Pop Culture
  - text: "Winter is coming."

# Fun Facts
  - text: "I loove pancakes."

# One Time
  # - text: "One time, on a road trip, the bottom of a bag of food fell out and the food got everywhere in the car.^500<br />My wife and I had our dog eat it.^500<br />Now that's what I call a win-win situation.^500<br />Good dog, Buddy."

# Food
  - text: "Doing the Hot Wing Challenge is not recommended."

# http://www.brandongoldman.com/

me-img: "/img/Looking up Colors - narrow circle - size medium.png"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: False
tumblr-share: False
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "personal-jekyll-theme"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/data_engineer_3.jpg"
    date: "Sept 2019 - Today"
    description: "Freelance Data Engineer"
  - image: "/img/timeline/price_charts_3.jpg"
    date: "Mar 2018 - Nov 2019"
    description: "Built a proprietary cross-exchange crypto market making trading engine"
  - image: "/img/timeline/dashboard_7.jpg"
    date: "Jan 2013 - Sep 2017"
    description: "Freelance Data Visualization Consultant"
  - image: "/img/timeline/study_5.jpg"
    date: "Sep 2009 - Jun 2012"
    description: "University of Leuven MSc Mechanical Engineering,<br>MSc Business Economics - Finance"

# First image of the Timeline

timeline-img: "/img/timeline/met_bal_3.jpg"

###########
# Contact #
###########

email: "koen.bal@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Koen Bal is a system builder. He lives in Europe, where he works on challenging engineering projects. In his spare time, Koen likes to eat pancakes."
author_blurb_image: "/img/Looking up Colors - narrow circle - size 100x100.png"

##################
# Social Buttons #
##################
# The title selects the desired icon from [Font Awesome](https://fortawesome.github.io/Font-Awesome/icons/)
social:

  - title: "github"
    url: "https://github.com/koenbal/"
  - title: "linkedin"
    url: "https://be.linkedin.com/in/koenbal"
  - title: "keybase"
    url: "https://keybase.io/koenbal" 
  - title: "twitter"
    url: "https://twitter.com/balkoen"
  - title: "medium"
    url: "https://medium.com/@koenbal"
  - title: "goodreads"
    url: "https://www.goodreads.com/koenbal" 
    
  # - title: "bitcoin"
  #   url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"


################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page
pages_list:
  About: 'about'
  # Blog: 'latest-post'
  Timeline: 'timeline'
  Expertise: 'expertise'
  More: 'more'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
